apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo-express
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=      # admin (base64)
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=  # admin123 (base64)
