apiVersion: v1
kind: Pod
metadata:
  name: busybox-hdd
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
